// This file is auto-generated by scripts/generate-index.js - do not edit manually!

import { ColorParser } from './core/ColorParser';
import { GeometryBuilder } from './core/GeometryBuilder';
import type { GeometryBuilderOptions } from './core/GeometryBuilder';
import { PathNormalizer } from './core/PathNormalizer';
import type { NormalizedContour, NormalizedPath, PathNormalizerOptions } from './core/PathNormalizer';
import { StyleResolver } from './core/StyleResolver';
import { Svg2GPU } from './core/Svg2GPU';
import { SVGParser } from './core/SvgParser';
import { Tessellator } from './core/Tessellator';
import { TransformParser } from './core/TransformParser';
import { WebGPURenderer } from './core/WebGPURenderer';
import type { WebGPURendererOptions } from './core/WebGPURenderer';
import { EPathDType, ESVGElementType } from './types/index';
import type { Point, Matrix2D, Color, TStrokeLineCap, TStrokeLineJoin, TVisibility, TDisplay, TFillRule, SVGStyleProps, PathCommand, SVGStrokeOnlyStyleProps, SVGPath, SVGCircle, SVGEllipse, SVGRect, SVGPolygon, SVGPolyline, SVGLine, SVGText, SVGGroup, SVGElmnt, SVGViewBox, SVGDocumentMetadata, ParsedSVGDocument, Svg2GPUDiagnosticLevel, Svg2GPUDiagnostic, ResolvedRenderStyle, ResolvedSVGElement, ResolvedScene, GeometryPrimitiveKind, GeometryBatch, GpuSceneStats, GpuScene, Svg2GPUFitMode, Svg2GPUOptions, Svg2GPUCompileOptions, MeshOutput, LineOutput, WebGLOutput } from './types/index';
import { Defaults } from './utils/Defaults';
import { Guard } from './utils/Guard';
import { Logger } from './utils/Logger';

export {
	ColorParser,
	GeometryBuilder,
	PathNormalizer,
	StyleResolver,
	Svg2GPU,
	SVGParser,
	Tessellator,
	TransformParser,
	WebGPURenderer,
	EPathDType,
	ESVGElementType,
	Defaults,
	Guard,
	Logger
};

export type {
	GeometryBuilderOptions,
	NormalizedContour,
	NormalizedPath,
	PathNormalizerOptions,
	WebGPURendererOptions,
	Point,
	Matrix2D,
	Color,
	TStrokeLineCap,
	TStrokeLineJoin,
	TVisibility,
	TDisplay,
	TFillRule,
	SVGStyleProps,
	PathCommand,
	SVGStrokeOnlyStyleProps,
	SVGPath,
	SVGCircle,
	SVGEllipse,
	SVGRect,
	SVGPolygon,
	SVGPolyline,
	SVGLine,
	SVGText,
	SVGGroup,
	SVGElmnt,
	SVGViewBox,
	SVGDocumentMetadata,
	ParsedSVGDocument,
	Svg2GPUDiagnosticLevel,
	Svg2GPUDiagnostic,
	ResolvedRenderStyle,
	ResolvedSVGElement,
	ResolvedScene,
	GeometryPrimitiveKind,
	GeometryBatch,
	GpuSceneStats,
	GpuScene,
	Svg2GPUFitMode,
	Svg2GPUOptions,
	Svg2GPUCompileOptions,
	MeshOutput,
	LineOutput,
	WebGLOutput
};
