const fs = require("fs");
const path = require("path");

const srcDir = path.join(__dirname, "../src");
const indexPath = path.join(srcDir, "index.ts");

function getAllModules(dir, baseDir = dir) {
	let modules = [];
	const files = fs.readdirSync(dir);
	for (const file of files) {
		const fullPath = path.join(dir, file);
		const relPath = path.relative(baseDir, fullPath).replace(/\\/g, "/");
		if (fs.statSync(fullPath).isDirectory()) {
			modules = modules.concat(getAllModules(fullPath, baseDir));
		} else if (file.endsWith(".ts") && relPath !== "index.ts") {
			modules.push(relPath.replace(/\.ts$/, ""));
		}
	}
	return modules;
}

function dedupeInOrder(items) {
	const seen = new Set();
	const result = [];
	for (const item of items) {
		if (!seen.has(item)) {
			seen.add(item);
			result.push(item);
		}
	}
	return result;
}

function parseExportList(specifierList) {
	return specifierList
		.split(",")
		.map((part) => part.trim())
		.filter(Boolean)
		.map((part) => part.split(/\s+as\s+/i)[0].trim())
		.filter(Boolean);
}

// Find named exports in a file and classify by kind
function getNamedExports(filePath) {
	const content = fs.readFileSync(filePath, "utf8");
	const valueExports = [];
	const typeExports = [];

	const declaredValueRegex = /export\s+(?:abstract\s+)?(?:class|function|const|let|var|enum)\s+([A-Za-z0-9_]+)/g;
	const declaredTypeRegex = /export\s+(?:type|interface)\s+([A-Za-z0-9_]+)/g;
	const exportTypeListRegex = /export\s+type\s*{([^}]+)}/g;
	const exportValueListRegex = /export\s*{([^}]+)}(?!\s*from)/g;

	let match;
	while ((match = declaredValueRegex.exec(content)) !== null) {
		valueExports.push(match[1]);
	}

	while ((match = declaredTypeRegex.exec(content)) !== null) {
		typeExports.push(match[1]);
	}

	while ((match = exportTypeListRegex.exec(content)) !== null) {
		typeExports.push(...parseExportList(match[1]));
	}

	while ((match = exportValueListRegex.exec(content)) !== null) {
		valueExports.push(...parseExportList(match[1]));
	}

	return {
		valueExports: dedupeInOrder(valueExports),
		typeExports: dedupeInOrder(typeExports),
	};
}

const modules = getAllModules(srcDir);

let importLines = [];
let valueExportNames = [];
let typeExportNames = [];

for (const mod of modules) {
	const absPath = path.join(srcDir, mod + ".ts");
	const { valueExports, typeExports } = getNamedExports(absPath);

	if (valueExports.length > 0) {
		importLines.push(`import { ${valueExports.join(", ")} } from './${mod}';`);
		valueExportNames.push(...valueExports);
	}

	if (typeExports.length > 0) {
		importLines.push(`import type { ${typeExports.join(", ")} } from './${mod}';`);
		typeExportNames.push(...typeExports);
	}
}

valueExportNames = dedupeInOrder(valueExportNames);
typeExportNames = dedupeInOrder(typeExportNames).filter(
	(name) => !valueExportNames.includes(name)
);

const valueExportBlock =
	valueExportNames.length > 0
		? `export {\n\t${valueExportNames.join(",\n\t")}\n};`
		: "";
const typeExportBlock =
	typeExportNames.length > 0
		? `export type {\n\t${typeExportNames.join(",\n\t")}\n};`
		: "";

const content = `// This file is auto-generated by scripts/generate-index.js - do not edit manually!

${importLines.join("\n")}

${valueExportBlock}
${valueExportBlock && typeExportBlock ? "\n" : ""}${typeExportBlock}
`;

fs.writeFileSync(indexPath, content);
console.log("src/index.ts generated.");
